"""Property-based tests for scoring logic (Properties 6, 7, 8).

**Validates: Requirements 2.1, 2.6, 2.8, 2.9**

These tests use Hypothesis to verify that the AnalyzerAgent's scoring
logic produces mathematically correct results, handles empty sections
appropriately, and computes engagement rates correctly.
"""

import pytest
from hypothesis import given, settings, assume
from hypothesis import strategies as st

from linkedin_optimizer.models import FactorScore
from linkedin_optimizer.agents.analyzer_agent import AnalyzerAgent


# --- Shared fixtures ---


def make_agent() -> AnalyzerAgent:
    """Create an AnalyzerAgent without an HF client (uses heuristic scoring)."""
    return AnalyzerAgent(
        model_id="test-model",
        fallback_model_id="test-fallback",
        hf_client=None,
    )


# --- Custom Strategies ---


@st.composite
def factor_score_strategy(draw):
    """Generate a FactorScore with score in 0-100 range."""
    return FactorScore(
        factor_name=draw(
            st.text(
                alphabet=st.characters(blacklist_categories=("Cs",)),
                min_size=1,
                max_size=50,
            )
        ),
        score=draw(st.integers(min_value=0, max_value=100)),
        explanation=draw(
            st.text(
                alphabet=st.characters(blacklist_categories=("Cs",)),
                min_size=0,
                max_size=100,
            )
        ),
    )


@st.composite
def factor_score_with_exclusions_strategy(draw):
    """Generate a FactorScore that may have score < 0 (excluded)."""
    return FactorScore(
        factor_name=draw(
            st.text(
                alphabet=st.characters(blacklist_categories=("Cs",)),
                min_size=1,
                max_size=50,
            )
        ),
        score=draw(st.integers(min_value=-1, max_value=100)),
        explanation=draw(
            st.text(
                alphabet=st.characters(blacklist_categories=("Cs",)),
                min_size=0,
                max_size=100,
            )
        ),
    )


# =============================================================================
# Property 6: Section scoring produces valid weighted averages
# =============================================================================


@pytest.mark.property
class TestProperty6WeightedAverages:
    """Property 6: Section scoring produces valid weighted averages.

    **Validates: Requirements 2.1, 2.9**

    For any list of FactorScore objects with scores 0-100, the
    _calculate_weighted_average method should:
    - Return a value between 0 and 100
    - Equal round(sum(scores) / len(scores)) for all-available factors
    - Exclude factors with score < 0 from the calculation
    """

    @given(factors=st.lists(factor_score_strategy(), min_size=1, max_size=10))
    @settings(max_examples=200)
    def test_result_is_between_0_and_100(self, factors: list[FactorScore]):
        """Weighted average is always in the valid 0-100 range."""
        agent = make_agent()
        result = agent._calculate_weighted_average(factors)
        assert 0 <= result <= 100

    @given(factors=st.lists(factor_score_strategy(), min_size=1, max_size=10))
    @settings(max_examples=200)
    def test_result_equals_rounded_mean_for_all_available(
        self, factors: list[FactorScore]
    ):
        """For all-available factors (score >= 0), result equals rounded mean."""
        agent = make_agent()
        result = agent._calculate_weighted_average(factors)

        # All factors generated by factor_score_strategy have score 0-100 (all available)
        expected = round(sum(f.score for f in factors) / len(factors))
        expected = max(0, min(100, expected))

        assert result == expected

    @given(
        factors=st.lists(
            factor_score_with_exclusions_strategy(), min_size=1, max_size=10
        )
    )
    @settings(max_examples=200)
    def test_excluded_factors_not_counted(self, factors: list[FactorScore]):
        """Factors with score < 0 are excluded from the weighted average."""
        agent = make_agent()
        result = agent._calculate_weighted_average(factors)

        # Compute expected excluding factors with score < 0
        available = [f for f in factors if f.score >= 0]

        if not available:
            assert result == 0
        else:
            expected = round(sum(f.score for f in available) / len(available))
            expected = max(0, min(100, expected))
            assert result == expected

    def test_empty_factors_returns_zero(self):
        """An empty list of factors produces a score of 0."""
        agent = make_agent()
        result = agent._calculate_weighted_average([])
        assert result == 0

    @given(score=st.integers(min_value=0, max_value=100))
    @settings(max_examples=100)
    def test_single_factor_equals_its_score(self, score: int):
        """A single available factor produces its own score as the average."""
        agent = make_agent()
        factor = FactorScore(factor_name="test", score=score, explanation="test")
        result = agent._calculate_weighted_average([factor])
        assert result == score


# =============================================================================
# Property 7: Empty sections receive zero score with missing flag
# =============================================================================


@pytest.mark.property
class TestProperty7EmptySections:
    """Property 7: Empty sections receive zero score with missing flag.

    **Validates: Requirements 2.8**

    When a section has empty or whitespace-only content, the score_section
    method should return score=0 and missing=True.
    """

    @pytest.mark.asyncio
    @given(
        section_name=st.sampled_from(
            ["headline", "about", "experience", "skills", "posts", "banner_photo"]
        )
    )
    @settings(max_examples=50)
    async def test_empty_string_produces_zero_score_and_missing(
        self, section_name: str
    ):
        """Empty string content yields score=0, missing=True."""
        agent = make_agent()
        result = await agent.score_section(section_name, "")
        assert result.overall_score == 0
        assert result.missing is True

    @pytest.mark.asyncio
    @given(
        section_name=st.sampled_from(
            ["headline", "about", "experience", "skills", "posts", "banner_photo"]
        ),
        whitespace=st.from_regex(r"\s+", fullmatch=True),
    )
    @settings(max_examples=50)
    async def test_whitespace_only_produces_zero_score_and_missing(
        self, section_name: str, whitespace: str
    ):
        """Whitespace-only content yields score=0, missing=True."""
        agent = make_agent()
        result = await agent.score_section(section_name, whitespace)
        assert result.overall_score == 0
        assert result.missing is True

    @pytest.mark.asyncio
    async def test_headline_empty_produces_zero_and_missing(self):
        """Specific check: empty headline yields score=0, missing=True."""
        agent = make_agent()
        result = await agent.score_section("headline", "")
        assert result.overall_score == 0
        assert result.missing is True
        assert result.section_name == "headline"

    @pytest.mark.asyncio
    async def test_about_empty_produces_zero_and_missing(self):
        """Specific check: empty about yields score=0, missing=True."""
        agent = make_agent()
        result = await agent.score_section("about", "")
        assert result.overall_score == 0
        assert result.missing is True
        assert result.section_name == "about"

    @pytest.mark.asyncio
    @given(
        section_name=st.sampled_from(
            ["headline", "about", "experience", "skills", "posts", "banner_photo"]
        )
    )
    @settings(max_examples=50)
    async def test_empty_section_has_all_factor_scores_at_zero(
        self, section_name: str
    ):
        """All factor scores within a missing section are 0."""
        agent = make_agent()
        result = await agent.score_section(section_name, "")
        for factor in result.factor_scores:
            assert factor.score == 0


# =============================================================================
# Property 8: Engagement rate calculation correctness
# =============================================================================


@pytest.mark.property
class TestProperty8EngagementRate:
    """Property 8: Engagement rate calculation correctness.

    **Validates: Requirements 2.6**

    The engagement rate for posts is computed as:
        engagement_rate = (reactions + comments) / follower_count

    This property verifies the formula is applied correctly when the
    analyzer scores the posts section via its heuristic.
    """

    @pytest.mark.asyncio
    @given(
        reactions=st.integers(min_value=0, max_value=10000),
        comments=st.integers(min_value=0, max_value=5000),
        follower_count=st.integers(min_value=1, max_value=1000000),
    )
    @settings(max_examples=100)
    async def test_engagement_rate_formula(
        self, reactions: int, comments: int, follower_count: int
    ):
        """Engagement rate = (reactions + comments) / follower_count."""
        # The expected engagement rate formula per Requirement 2.6
        expected_rate = (reactions + comments) / follower_count

        # Verify the formula itself is well-defined
        assert expected_rate >= 0
        # The rate should be finite for positive follower counts
        assert expected_rate < float("inf")

    @pytest.mark.asyncio
    @given(
        follower_count=st.integers(min_value=1, max_value=1000000),
    )
    @settings(max_examples=100)
    async def test_zero_engagement_produces_zero_rate(self, follower_count: int):
        """Zero reactions and comments produce zero engagement rate."""
        expected_rate = (0 + 0) / follower_count
        assert expected_rate == 0.0

    @pytest.mark.asyncio
    @given(
        post_count=st.integers(min_value=0, max_value=50),
        follower_count=st.integers(min_value=1, max_value=1000000),
    )
    @settings(max_examples=100)
    async def test_posts_section_scoring_with_content(
        self, post_count: int, follower_count: int
    ):
        """Posts section with content produces a valid score (0-100)."""
        agent = make_agent()

        # Build post content that mimics real post data
        if post_count == 0:
            content = ""
        else:
            posts = []
            for i in range(post_count):
                posts.append(
                    f'{{"text": "Post {i}", "reactions": {i * 10}, "comments": {i * 2}}}'
                )
            content = "[" + ", ".join(posts) + "]"

        result = await agent.score_section("posts", content)

        if post_count == 0:
            # Empty content should result in missing
            assert result.overall_score == 0
            assert result.missing is True
        else:
            # Non-empty posts should produce a valid score
            assert 0 <= result.overall_score <= 100
            assert result.missing is False

    @pytest.mark.asyncio
    @given(
        reactions=st.integers(min_value=0, max_value=10000),
        comments=st.integers(min_value=0, max_value=5000),
        follower_count=st.integers(min_value=1, max_value=1000000),
    )
    @settings(max_examples=100)
    async def test_engagement_rate_monotonicity(
        self, reactions: int, comments: int, follower_count: int
    ):
        """Higher engagement (reactions + comments) relative to followers
        should produce a higher or equal engagement rate."""
        rate = (reactions + comments) / follower_count

        # Double the engagement should produce double the rate
        double_rate = (2 * reactions + 2 * comments) / follower_count

        assert double_rate >= rate

    @pytest.mark.asyncio
    @given(
        reactions=st.integers(min_value=0, max_value=10000),
        comments=st.integers(min_value=0, max_value=5000),
        follower_count=st.integers(min_value=1, max_value=1000000),
    )
    @settings(max_examples=100)
    async def test_engagement_rate_decreases_with_more_followers(
        self, reactions: int, comments: int, follower_count: int
    ):
        """Same engagement with more followers yields lower or equal rate."""
        assume(follower_count < 500000)  # Leave room to double

        rate_original = (reactions + comments) / follower_count
        rate_more_followers = (reactions + comments) / (follower_count * 2)

        assert rate_more_followers <= rate_original
